NOMBRE_DSD: DSD_SOCMER
categoria: SIN DEFINIR
grupos_consultas:
  Sociedades mercantiles:
    id: '1'
    consultas:
    - '65646'
    - '28098'
  Sociedades mercantiles constituidas:
    id: '2'
    consultas:
    - '497'
    - '65647'
variables:
- TEMPORAL
- TERRITORIO
- FORMA_JUR_SOCMER
- ESTADO_DATO
- INDICATOR
- OBS_VALUE
- FREQ
- CNAE09
- SEXO_SOCIOS
