NOMBRE_DSD: DSD_DSN
categoria: POP_MIGRATION
grupos_consultas:
  Disoluciones según la edad de los cónyuges por provincia de residencia:
    id: '1'
    consultas:
    - '64486'
  Divorcios, separaciones y nulidades según sexo por provincia de residencia:
    id: '2'
    consultas:
    - '64491'
  Divorcios, separaciones y nulidades según el estado civil previo al matrimonio por provincia de residencia:
    id: '3'
    consultas:
    - '64490'
  Disoluciones según duración del matrimonio por provincia de residencia:
    id: '4'
    consultas:
    - '64492'
  Disoluciones según número de hijos menores de edad:
    id: '5'
    consultas:
    - '64509'
  Disoluciones según cónyuge que ejerce la custodia:
    id: '6'
    consultas:
    - '64510'
  Disoluciones según la nacionalidad de los cónyuges:
    id: '7'
    consultas:
    - '64511'
  Divorcios, separaciones y nulidades entre cónyuges del mismo sexo:
    id: '8'
    consultas:
    - '64512'
variables:
- TEMPORAL
- TERRITORIO
- EDAD
- EDADC2
- INDICATOR
- OBS_VALUE
- FREQ
- SEXO
- SEXOC2
- ESTADOCIVIL
- ESTADOCIVILC2
- DURACMATRIM
- NUMHIJOSMENORED
- CUSTODIA
- NACIONACONYUGES
- TIPOMATRIMONIO
