NOMBRE_DSD: DSD_EPD
categoria: SIN DEFINIR
grupos_consultas:
  'Población: Prevalencia de la discapacidad':
    id: '1'
    consultas:
    - '66383'
    - '66384'
  Educación:
    id: '2'
    consultas:
    - '66385'
  Relación con la actividad:
    id: '3'
    consultas:
    - '66386'
  Ocupación:
    id: '4'
    consultas:
    - '66387'
  Percepción de prestaciones:
    id: '5'
    consultas:
    - '66388'
  Situación de dependencia:
    id: '6'
    consultas:
    - '66390'
  Hogares:
    id: '7'
    consultas:
    - '66391'
variables:
- SEXO
- EPD_GRUPOSEDAD
- TEMPORAL
- CERTIFICDISCAPAC
- TERRITORIO
- INDICATOR
- OBS_VALUE
- FREQ
- ESTADOCIVIL
- EPD_NIVELESTUDIOSTER
- EPD_RELACTIVIDAD
- EPD_SITUACPROFES
- EPD_PERCEPPRESINVAL
- EPD_SITUACIONDEPEND
- EPD_COMPHOGACTIVIDAD
- EPD_PRESENCDISCAPAC
- EPD_AMBITOESTUDHOG
