NOMBRE_DSD: DSD_ECTA
categoria: TOURISM
grupos_consultas:
  Número de turistas. Anual.:
    id: '1'
    consultas:
    - '20071'
  Porcentaje de turistas por procedencia y sexo:
    id: '2'
    consultas:
    - '2218'
  Porcentaje de turistas por provincia de destino principal:
    id: '3'
    consultas:
    - '9282'
  Porcentaje de viajes por tipo de alojamiento:
    id: '4'
    consultas:
    - '8450'
  Estancia media de los turistas por procedencia:
    id: '5'
    consultas:
    - '29331'
  Estancia media por provincia:
    id: '6'
    consultas:
    - '29333'
  Estancia media de los turistas por tipo de alojamiento:
    id: '7'
    consultas:
    - '2421'
  Gasto medio diario de los turistas por procedencia:
    id: '8'
    consultas:
    - '29332'
  Gasto medio diario de los turistas por provincia:
    id: '9'
    consultas:
    - '29334'
variables:
- TEMPORAL
- INDICATOR
- OBS_VALUE
- FREQ
- SEXO
- PROCEDENCIA_ECTA
- TERRITORIO
- TIPO_ALOJAM_ECTA
